language: go
services: mysql

install: true

go:
  - 1.9

script:
  - |
    set -e
    echo > coverage.txt
    for package in go-bouncer/{,mozlog,bouncer}; do
      go test -v -covermode=atomic -coverprofile=profile.out "github.com/mozilla-services/${package}"
      if [ -f profile.out ]; then
        cat profile.out >> coverage.txt
      fi
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)
